language: php

dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script: composer test